"""initial_schema

Revision ID: b930f4bab752
Revises: 001
Create Date: 2026-07-29 20:37:41.917733
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'b930f4bab752'
down_revision: Union[str, None] = '001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cves', sa.Column('cvss_v2', sa.Float(), nullable=True))
    op.add_column('cves', sa.Column('cvss_v3', sa.Float(), nullable=True))
    op.add_column('cves', sa.Column('base_score', sa.Float(), nullable=True))
    op.add_column('cves', sa.Column('exploitability_score', sa.Float(), nullable=True))
    op.add_column('cves', sa.Column('impact_score', sa.Float(), nullable=True))
    op.add_column('cves', sa.Column('last_modified', sa.DateTime(timezone=True), nullable=True))
    op.add_column('cves', sa.Column('epss_score', sa.Float(), nullable=True))
    op.add_column('cves', sa.Column('kev_status', sa.Boolean(), nullable=False))
    op.add_column('cves', sa.Column('source', sa.String(length=50), nullable=True))
    op.add_column('cves', sa.Column('vendor', sa.String(length=255), nullable=True))
    op.add_column('cves', sa.Column('product', sa.String(length=255), nullable=True))
    op.add_column('cves', sa.Column('affected_versions', postgresql.ARRAY(sa.String()), nullable=True))
    op.add_column('cves', sa.Column('remediation_priority', sa.String(length=20), nullable=True))
    op.alter_column('cves', 'exploit_available',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('cves', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('cves', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_cves_cve_id'), table_name='cves')
    op.drop_index(op.f('idx_cves_msf_module'), table_name='cves')
    op.create_index(op.f('ix_cves_cve_id'), 'cves', ['cve_id'], unique=False)
    op.create_index(op.f('ix_cves_metasploit_module'), 'cves', ['metasploit_module'], unique=False)
    op.create_index(op.f('ix_cves_remediation_priority'), 'cves', ['remediation_priority'], unique=False)
    op.create_index(op.f('ix_cves_vuln_id'), 'cves', ['vuln_id'], unique=False)
    op.alter_column('exploit_runs', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'pending'::character varying"))
    op.alter_column('exploit_runs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('exploit_runs', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_exploit_runs_exploit_id'), table_name='exploit_runs')
    op.drop_index(op.f('idx_exploit_runs_host_id'), table_name='exploit_runs')
    op.drop_index(op.f('idx_exploit_runs_status'), table_name='exploit_runs')
    op.create_index(op.f('ix_exploit_runs_exploit_id'), 'exploit_runs', ['exploit_id'], unique=False)
    op.create_index(op.f('ix_exploit_runs_host_id'), 'exploit_runs', ['host_id'], unique=False)
    op.create_index(op.f('ix_exploit_runs_status'), 'exploit_runs', ['status'], unique=False)
    op.add_column('exploits', sa.Column('vulnerability_id', sa.UUID(), nullable=True))
    op.add_column('exploits', sa.Column('service_id', sa.UUID(), nullable=True))
    op.add_column('exploits', sa.Column('provider', sa.String(length=50), nullable=False))
    op.add_column('exploits', sa.Column('exploit_name', sa.String(length=500), nullable=True))
    op.add_column('exploits', sa.Column('cve', sa.String(length=20), nullable=True))
    op.add_column('exploits', sa.Column('verified', sa.Boolean(), nullable=False))
    op.add_column('exploits', sa.Column('execution_mode', sa.String(length=20), nullable=False))
    op.add_column('exploits', sa.Column('status', sa.String(length=20), nullable=False))
    op.add_column('exploits', sa.Column('risk_level', sa.String(length=20), nullable=True))
    op.add_column('exploits', sa.Column('confidence', sa.Integer(), nullable=True))
    op.add_column('exploits', sa.Column('session_created', sa.Boolean(), nullable=False))
    op.add_column('exploits', sa.Column('session_type', sa.String(length=50), nullable=True))
    op.add_column('exploits', sa.Column('start_time', sa.DateTime(timezone=True), nullable=True))
    op.add_column('exploits', sa.Column('end_time', sa.DateTime(timezone=True), nullable=True))
    op.add_column('exploits', sa.Column('duration', sa.Float(), nullable=True))
    op.add_column('exploits', sa.Column('output', sa.Text(), nullable=True))
    op.add_column('exploits', sa.Column('error', sa.Text(), nullable=True))
    op.alter_column('exploits', 'module_name',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)
    op.alter_column('exploits', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('exploits', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_exploits_host_id'), table_name='exploits')
    op.create_index(op.f('ix_exploits_execution_mode'), 'exploits', ['execution_mode'], unique=False)
    op.create_index(op.f('ix_exploits_host_id'), 'exploits', ['host_id'], unique=False)
    op.create_index(op.f('ix_exploits_service_id'), 'exploits', ['service_id'], unique=False)
    op.create_index(op.f('ix_exploits_status'), 'exploits', ['status'], unique=False)
    op.create_index(op.f('ix_exploits_vulnerability_id'), 'exploits', ['vulnerability_id'], unique=False)
    op.drop_constraint(op.f('exploits_cve_id_fkey'), 'exploits', type_='foreignkey')
    op.create_foreign_key(None, 'exploits', 'services', ['service_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'exploits', 'vulnerabilities', ['vulnerability_id'], ['id'], ondelete='SET NULL')
    op.drop_column('exploits', 'description')
    op.drop_column('exploits', 'cve_id')
    op.drop_column('exploits', 'module_type')
    op.drop_column('exploits', 'payloads')
    op.drop_column('exploits', 'target')
    op.drop_column('exploits', 'rank')
    op.alter_column('hosts', 'ip_address',
               existing_type=sa.VARCHAR(),
               type_=postgresql.INET(),
               existing_nullable=False,
               postgresql_using='ip_address::inet')
    op.alter_column('hosts', 'mac_address',
               existing_type=sa.VARCHAR(),
               type_=postgresql.MACADDR(),
               existing_nullable=True,
               postgresql_using='mac_address::macaddr')
    op.alter_column('hosts', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'unknown'::character varying"))
    op.alter_column('hosts', 'is_alive',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('hosts', 'first_seen',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('hosts', 'last_seen',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('hosts', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('hosts', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_hosts_ip'), table_name='hosts')
    op.drop_index(op.f('idx_hosts_scan_id'), table_name='hosts')
    op.drop_index(op.f('idx_hosts_status'), table_name='hosts')
    op.create_index(op.f('ix_hosts_ip_address'), 'hosts', ['ip_address'], unique=False)
    op.create_index(op.f('ix_hosts_scan_id'), 'hosts', ['scan_id'], unique=False)
    op.create_index(op.f('ix_hosts_status'), 'hosts', ['status'], unique=False)
    op.alter_column('logs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_logs_created'), table_name='logs')
    op.drop_index(op.f('idx_logs_level_module'), table_name='logs')
    op.create_index(op.f('ix_logs_created_at'), 'logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_logs_level'), 'logs', ['level'], unique=False)
    op.create_index(op.f('ix_logs_module'), 'logs', ['module'], unique=False)
    op.alter_column('packet_captures', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('packet_captures', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_packet_captures_scan_id'), 'packet_captures', ['scan_id'], unique=False)
    op.alter_column('ports', 'protocol',
               existing_type=sa.VARCHAR(length=10),
               nullable=False,
               existing_server_default=sa.text("'tcp'::character varying"))
    op.alter_column('ports', 'state',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'unknown'::character varying"))
    op.alter_column('ports', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('ports', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_ports_host_id'), table_name='ports')
    op.drop_index(op.f('idx_ports_state'), table_name='ports')
    op.create_index(op.f('ix_ports_host_id'), 'ports', ['host_id'], unique=False)
    op.create_index(op.f('ix_ports_state'), 'ports', ['state'], unique=False)
    op.alter_column('reports', 'include_exec_summary',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('reports', 'include_technical',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('reports', 'include_recommendations',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('reports', 'generated_by',
               existing_type=sa.VARCHAR(length=255),
               nullable=False,
               existing_server_default=sa.text("'system'::character varying"))
    op.alter_column('reports', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('reports', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_reports_scan_id'), table_name='reports')
    op.create_index(op.f('ix_reports_scan_id'), 'reports', ['scan_id'], unique=False)
    op.alter_column('scans', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'pending'::character varying"))
    op.alter_column('scans', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('scans', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_scans_status'), table_name='scans')
    op.drop_index(op.f('idx_scans_type'), table_name='scans')
    op.create_index(op.f('ix_scans_scan_type'), 'scans', ['scan_type'], unique=False)
    op.create_index(op.f('ix_scans_status'), 'scans', ['status'], unique=False)
    op.add_column('services', sa.Column('normalized_name', sa.String(length=255), nullable=True))
    op.add_column('services', sa.Column('normalized_product', sa.String(length=255), nullable=True))
    op.add_column('services', sa.Column('normalized_version', sa.String(length=255), nullable=True))
    op.add_column('services', sa.Column('category', sa.String(length=100), nullable=True))
    op.add_column('services', sa.Column('confidence', sa.Integer(), nullable=True))
    op.add_column('services', sa.Column('notes', sa.Text(), nullable=True))
    op.alter_column('services', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('services', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_services_name'), table_name='services')
    op.drop_index(op.f('idx_services_port_id'), table_name='services')
    op.create_index(op.f('ix_services_category'), 'services', ['category'], unique=False)
    op.create_index(op.f('ix_services_name'), 'services', ['name'], unique=False)
    op.create_index(op.f('ix_services_normalized_name'), 'services', ['normalized_name'], unique=False)
    op.create_index(op.f('ix_services_port_id'), 'services', ['port_id'], unique=False)
    op.alter_column('settings', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('settings', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_settings_key'), table_name='settings')
    op.drop_constraint(op.f('settings_key_key'), 'settings', type_='unique')
    op.create_index(op.f('ix_settings_key'), 'settings', ['key'], unique=True)
    op.add_column('vulnerabilities', sa.Column('service_id', sa.UUID(), nullable=True))
    op.add_column('vulnerabilities', sa.Column('cwe', postgresql.ARRAY(sa.String()), nullable=True))
    op.add_column('vulnerabilities', sa.Column('scanner_name', sa.String(length=100), nullable=True))
    op.add_column('vulnerabilities', sa.Column('scanner_id', sa.String(length=200), nullable=True))
    op.add_column('vulnerabilities', sa.Column('status', sa.String(length=20), nullable=True))
    op.add_column('vulnerabilities', sa.Column('affected_product', sa.String(length=255), nullable=True))
    op.add_column('vulnerabilities', sa.Column('affected_version', sa.String(length=255), nullable=True))
    op.add_column('vulnerabilities', sa.Column('evidence', sa.Text(), nullable=True))
    op.add_column('vulnerabilities', sa.Column('raw_scanner_output', sa.Text(), nullable=True))
    op.add_column('vulnerabilities', sa.Column('confidence', sa.Integer(), nullable=True))
    op.add_column('vulnerabilities', sa.Column('references', postgresql.ARRAY(sa.Text()), nullable=True))
    op.add_column('vulnerabilities', sa.Column('cve_count', sa.Integer(), nullable=True))
    op.alter_column('vulnerabilities', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('vulnerabilities', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_vulns_host_id'), table_name='vulnerabilities')
    op.drop_index(op.f('idx_vulns_severity'), table_name='vulnerabilities')
    op.create_index(op.f('ix_vulnerabilities_host_id'), 'vulnerabilities', ['host_id'], unique=False)
    op.create_index(op.f('ix_vulnerabilities_scan_id'), 'vulnerabilities', ['scan_id'], unique=False)
    op.create_index(op.f('ix_vulnerabilities_scanner_name'), 'vulnerabilities', ['scanner_name'], unique=False)
    op.create_index(op.f('ix_vulnerabilities_service_id'), 'vulnerabilities', ['service_id'], unique=False)
    op.create_index(op.f('ix_vulnerabilities_severity'), 'vulnerabilities', ['severity'], unique=False)
    op.create_index(op.f('ix_vulnerabilities_status'), 'vulnerabilities', ['status'], unique=False)
    op.create_foreign_key(None, 'vulnerabilities', 'services', ['service_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'vulnerabilities', type_='foreignkey')
    op.drop_index(op.f('ix_vulnerabilities_status'), table_name='vulnerabilities')
    op.drop_index(op.f('ix_vulnerabilities_severity'), table_name='vulnerabilities')
    op.drop_index(op.f('ix_vulnerabilities_service_id'), table_name='vulnerabilities')
    op.drop_index(op.f('ix_vulnerabilities_scanner_name'), table_name='vulnerabilities')
    op.drop_index(op.f('ix_vulnerabilities_scan_id'), table_name='vulnerabilities')
    op.drop_index(op.f('ix_vulnerabilities_host_id'), table_name='vulnerabilities')
    op.create_index(op.f('idx_vulns_severity'), 'vulnerabilities', ['severity'], unique=False)
    op.create_index(op.f('idx_vulns_host_id'), 'vulnerabilities', ['host_id'], unique=False)
    op.alter_column('vulnerabilities', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('vulnerabilities', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_column('vulnerabilities', 'cve_count')
    op.drop_column('vulnerabilities', 'references')
    op.drop_column('vulnerabilities', 'confidence')
    op.drop_column('vulnerabilities', 'raw_scanner_output')
    op.drop_column('vulnerabilities', 'evidence')
    op.drop_column('vulnerabilities', 'affected_version')
    op.drop_column('vulnerabilities', 'affected_product')
    op.drop_column('vulnerabilities', 'status')
    op.drop_column('vulnerabilities', 'scanner_id')
    op.drop_column('vulnerabilities', 'scanner_name')
    op.drop_column('vulnerabilities', 'cwe')
    op.drop_column('vulnerabilities', 'service_id')
    op.drop_index(op.f('ix_settings_key'), table_name='settings')
    op.create_unique_constraint(op.f('settings_key_key'), 'settings', ['key'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_settings_key'), 'settings', ['key'], unique=False)
    op.alter_column('settings', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('settings', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_services_port_id'), table_name='services')
    op.drop_index(op.f('ix_services_normalized_name'), table_name='services')
    op.drop_index(op.f('ix_services_name'), table_name='services')
    op.drop_index(op.f('ix_services_category'), table_name='services')
    op.create_index(op.f('idx_services_port_id'), 'services', ['port_id'], unique=False)
    op.create_index(op.f('idx_services_name'), 'services', ['name'], unique=False)
    op.alter_column('services', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('services', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_column('services', 'notes')
    op.drop_column('services', 'confidence')
    op.drop_column('services', 'category')
    op.drop_column('services', 'normalized_version')
    op.drop_column('services', 'normalized_product')
    op.drop_column('services', 'normalized_name')
    op.drop_index(op.f('ix_scans_status'), table_name='scans')
    op.drop_index(op.f('ix_scans_scan_type'), table_name='scans')
    op.create_index(op.f('idx_scans_type'), 'scans', ['scan_type'], unique=False)
    op.create_index(op.f('idx_scans_status'), 'scans', ['status'], unique=False)
    op.alter_column('scans', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('scans', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('scans', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'pending'::character varying"))
    op.drop_index(op.f('ix_reports_scan_id'), table_name='reports')
    op.create_index(op.f('idx_reports_scan_id'), 'reports', ['scan_id'], unique=False)
    op.alter_column('reports', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('reports', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('reports', 'generated_by',
               existing_type=sa.VARCHAR(length=255),
               nullable=True,
               existing_server_default=sa.text("'system'::character varying"))
    op.alter_column('reports', 'include_recommendations',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('reports', 'include_technical',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('reports', 'include_exec_summary',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.drop_index(op.f('ix_ports_state'), table_name='ports')
    op.drop_index(op.f('ix_ports_host_id'), table_name='ports')
    op.create_index(op.f('idx_ports_state'), 'ports', ['state'], unique=False)
    op.create_index(op.f('idx_ports_host_id'), 'ports', ['host_id'], unique=False)
    op.alter_column('ports', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('ports', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('ports', 'state',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'unknown'::character varying"))
    op.alter_column('ports', 'protocol',
               existing_type=sa.VARCHAR(length=10),
               nullable=True,
               existing_server_default=sa.text("'tcp'::character varying"))
    op.drop_index(op.f('ix_packet_captures_scan_id'), table_name='packet_captures')
    op.alter_column('packet_captures', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('packet_captures', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_logs_module'), table_name='logs')
    op.drop_index(op.f('ix_logs_level'), table_name='logs')
    op.drop_index(op.f('ix_logs_created_at'), table_name='logs')
    op.create_index(op.f('idx_logs_level_module'), 'logs', ['level', 'module'], unique=False)
    op.create_index(op.f('idx_logs_created'), 'logs', ['created_at'], unique=False)
    op.alter_column('logs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_hosts_status'), table_name='hosts')
    op.drop_index(op.f('ix_hosts_scan_id'), table_name='hosts')
    op.drop_index(op.f('ix_hosts_ip_address'), table_name='hosts')
    op.create_index(op.f('idx_hosts_status'), 'hosts', ['status'], unique=False)
    op.create_index(op.f('idx_hosts_scan_id'), 'hosts', ['scan_id'], unique=False)
    op.create_index(op.f('idx_hosts_ip'), 'hosts', ['ip_address'], unique=False)
    op.alter_column('hosts', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('hosts', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('hosts', 'last_seen',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('hosts', 'first_seen',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('hosts', 'is_alive',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('hosts', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'unknown'::character varying"))
    op.alter_column('hosts', 'mac_address',
               existing_type=postgresql.MACADDR(),
               type_=sa.VARCHAR(),
               existing_nullable=True,
               postgresql_using='mac_address::varchar')
    op.alter_column('hosts', 'ip_address',
               existing_type=postgresql.INET(),
               type_=sa.VARCHAR(),
               existing_nullable=False,
               postgresql_using='ip_address::varchar')
    op.add_column('exploits', sa.Column('rank', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('exploits', sa.Column('target', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('exploits', sa.Column('payloads', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('exploits', sa.Column('module_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('exploits', sa.Column('cve_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('exploits', sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'exploits', type_='foreignkey')
    op.drop_constraint(None, 'exploits', type_='foreignkey')
    op.create_foreign_key(op.f('exploits_cve_id_fkey'), 'exploits', 'cves', ['cve_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_exploits_vulnerability_id'), table_name='exploits')
    op.drop_index(op.f('ix_exploits_status'), table_name='exploits')
    op.drop_index(op.f('ix_exploits_service_id'), table_name='exploits')
    op.drop_index(op.f('ix_exploits_host_id'), table_name='exploits')
    op.drop_index(op.f('ix_exploits_execution_mode'), table_name='exploits')
    op.create_index(op.f('idx_exploits_host_id'), 'exploits', ['host_id'], unique=False)
    op.alter_column('exploits', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('exploits', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('exploits', 'module_name',
               existing_type=sa.VARCHAR(length=500),
               nullable=False)
    op.drop_column('exploits', 'error')
    op.drop_column('exploits', 'output')
    op.drop_column('exploits', 'duration')
    op.drop_column('exploits', 'end_time')
    op.drop_column('exploits', 'start_time')
    op.drop_column('exploits', 'session_type')
    op.drop_column('exploits', 'session_created')
    op.drop_column('exploits', 'confidence')
    op.drop_column('exploits', 'risk_level')
    op.drop_column('exploits', 'status')
    op.drop_column('exploits', 'execution_mode')
    op.drop_column('exploits', 'verified')
    op.drop_column('exploits', 'cve')
    op.drop_column('exploits', 'exploit_name')
    op.drop_column('exploits', 'provider')
    op.drop_column('exploits', 'service_id')
    op.drop_column('exploits', 'vulnerability_id')
    op.drop_index(op.f('ix_exploit_runs_status'), table_name='exploit_runs')
    op.drop_index(op.f('ix_exploit_runs_host_id'), table_name='exploit_runs')
    op.drop_index(op.f('ix_exploit_runs_exploit_id'), table_name='exploit_runs')
    op.create_index(op.f('idx_exploit_runs_status'), 'exploit_runs', ['status'], unique=False)
    op.create_index(op.f('idx_exploit_runs_host_id'), 'exploit_runs', ['host_id'], unique=False)
    op.create_index(op.f('idx_exploit_runs_exploit_id'), 'exploit_runs', ['exploit_id'], unique=False)
    op.alter_column('exploit_runs', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('exploit_runs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('exploit_runs', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'pending'::character varying"))
    op.drop_index(op.f('ix_cves_vuln_id'), table_name='cves')
    op.drop_index(op.f('ix_cves_remediation_priority'), table_name='cves')
    op.drop_index(op.f('ix_cves_metasploit_module'), table_name='cves')
    op.drop_index(op.f('ix_cves_cve_id'), table_name='cves')
    op.create_index(op.f('idx_cves_msf_module'), 'cves', ['metasploit_module'], unique=False)
    op.create_index(op.f('idx_cves_cve_id'), 'cves', ['cve_id'], unique=False)
    op.alter_column('cves', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('cves', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('cves', 'exploit_available',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.drop_column('cves', 'remediation_priority')
    op.drop_column('cves', 'affected_versions')
    op.drop_column('cves', 'product')
    op.drop_column('cves', 'vendor')
    op.drop_column('cves', 'source')
    op.drop_column('cves', 'kev_status')
    op.drop_column('cves', 'epss_score')
    op.drop_column('cves', 'last_modified')
    op.drop_column('cves', 'impact_score')
    op.drop_column('cves', 'exploitability_score')
    op.drop_column('cves', 'base_score')
    op.drop_column('cves', 'cvss_v3')
    op.drop_column('cves', 'cvss_v2')
    # ### end Alembic commands ###
